//! Generated terminal configuration: the startup ini, the EA preset and (as a
//! fallback) a chart profile.
//!
//! The formats are the ones documented by MetaTrader 5 itself
//! ("Platform Start — For Advanced Users"): the terminal is launched with
//! `/portable /config:<file>`, the file carries `[Common]` (account),
//! `[Experts]` (the automated-trading master switches) and `[StartUp]` (which
//! EA to attach, on which symbol and period, with which preset). That is what
//! makes this host fully unattended — no clicking in a GUI, ever. That is the
//! whole point of writing these files from Rust: it supersedes the earlier
//! Windows/Wine-desktop deployment assumption, where attaching the EA and
//! logging the terminal in were manual steps in a window nobody can see here.
//!
//! `[StartUp] ExpertParameters` must be a **file name** that lives in
//! `MQL5\Presets` of the platform data directory, so [`preset`] is written
//! there by the supervisor.

use crate::config::Config;

/// The Expert Advisor source, compiled into this binary so the image never
/// depends on the repository layout at runtime.
pub const EA_SOURCE: &str = include_str!("../../mt5-bridge/mql5/Mt5BridgeEA.mq5");

/// `[StartUp] Expert=` wants a path below `MQL5\Experts`, without extension.
pub fn expert_reference(config: &Config) -> String {
    format!("{}\\{}", crate::config::EA_SUBDIR, config.ea_name)
}

/// The terminal startup ini. Contains the account password: the supervisor
/// writes it with `0600` and deletes it once the terminal has read it.
pub fn start_ini(config: &Config) -> String {
    let login = config.login.as_deref().unwrap_or_default();
    let password = config.password.as_deref().unwrap_or_default();
    let server = config.server.as_deref().unwrap_or_default();
    format!(
        "; generated by mt5-host — do not edit, it is rewritten on every boot\r\n\
         ; Node 4 owns venue policy; this file only tells the terminal which demo\r\n\
         ; account to log into and to attach the bridge EA on startup.\r\n\
         [Common]\r\n\
         Login={login}\r\n\
         Password={password}\r\n\
         Server={server}\r\n\
         ProxyEnable=0\r\n\
         NewsEnable=0\r\n\
         CertInstall=0\r\n\
         \r\n\
         [Charts]\r\n\
         ProfileLast=Default\r\n\
         MaxBars=5000\r\n\
         SaveDeleted=0\r\n\
         TradeHistory=1\r\n\
         \r\n\
         [Experts]\r\n\
         AllowLiveTrading=1\r\n\
         AllowDllImport=0\r\n\
         Enabled=1\r\n\
         Account=1\r\n\
         Profile=1\r\n\
         Chart=0\r\n\
         Api=0\r\n\
         WebRequest=0\r\n\
         \r\n\
         [StartUp]\r\n\
         Expert={expert}\r\n\
         Symbol={symbol}\r\n\
         Period={period}\r\n\
         ExpertParameters={preset}\r\n",
        expert = expert_reference(config),
        symbol = config.symbol,
        period = config.period,
        preset = preset_file_name(config),
    )
}

pub fn preset_file_name(config: &Config) -> String {
    format!("{}.set", config.ea_name)
}

/// The EA preset (`.set`), i.e. the EA's own inputs: the loopback address of
/// the bridge, the shared EA token, the symbols it may touch, the magic number.
pub fn preset(config: &Config) -> String {
    format!(
        "; generated by mt5-host — the EA's inputs, applied at startup\r\n\
         InpBridgeHost=127.0.0.1\r\n\
         InpBridgePort={port}\r\n\
         InpToken={token}\r\n\
         InpAllowedSymbols={symbols}\r\n\
         InpHeartbeatSecs=5\r\n\
         InpMagicFilter={magic}\r\n\
         InpVerbose=false\r\n",
        port = config.ea_port,
        token = config.ea_token.as_deref().unwrap_or_default(),
        symbols = config.allowed_symbols(),
        magic = config.magic,
    )
}

/// Optional fallback: a chart profile that already has the EA attached.
///
/// Not used unless `MT5_HOST_WRITE_PROFILE=1`. The `[StartUp]` route above is
/// the documented one; this exists for terminals whose profile was already
/// created by hand and that ignore `Expert=` for one reason or another.
pub fn chart_profile(config: &Config) -> String {
    format!(
        "<chart>\r\n\
         id=1\r\n\
         symbol={symbol}\r\n\
         period={period}\r\n\
         digits=3\r\n\
         mode=1\r\n\
         volume=0\r\n\
         <expert>\r\n\
         name={expert}\r\n\
         flags=347\r\n\
         window_num=0\r\n\
         <inputs>\r\n\
         InpBridgeHost=127.0.0.1\r\n\
         InpBridgePort={port}\r\n\
         InpToken={token}\r\n\
         InpAllowedSymbols={symbols}\r\n\
         InpHeartbeatSecs=5\r\n\
         InpMagicFilter={magic}\r\n\
         InpVerbose=false\r\n\
         </inputs>\r\n\
         </expert>\r\n\
         </chart>\r\n",
        symbol = config.symbol,
        period = config.period,
        expert = expert_reference(config),
        port = config.ea_port,
        token = config.ea_token.as_deref().unwrap_or_default(),
        symbols = config.allowed_symbols(),
        magic = config.magic,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn config() -> Config {
        Config {
            port: 10_000,
            state_dir: PathBuf::from("/data"),
            prepare_only: false,
            display: ":99".into(),
            screen: "640x480x16".into(),
            xvfb_bin: "Xvfb".into(),
            wine_bin: "wine".into(),
            wine_prefix: PathBuf::from("/data/wine"),
            wineboot_extra_args: Vec::new(),
            installer_path: PathBuf::from("/opt/mt5/mt5setup.exe"),
            installer_url: "https://example.invalid/mt5setup.exe".into(),
            prefix_archive_url: None,
            tar_bin: "tar".into(),
            curl_bin: "curl".into(),
            login: Some("123456".into()),
            password: Some("hunter2".into()),
            server: Some("Deriv-Demo".into()),
            manual_login: false,
            symbol: "XAUUSD".into(),
            period: "1".into(),
            ea_name: "Mt5BridgeEA".into(),
            ea_source: None,
            ea_token: Some("ea-token".into()),
            ea_port: 5055,
            magic: 330_033,
            allowed_symbols: None,
            extra_terminal_args: Vec::new(),
            write_profile: false,
            bridge_bin: PathBuf::from("mt5-bridge"),
            node4_ws_url: Some("wss://node4.example/mt5/bridge".into()),
            bridge_token: Some("bridge-token".into()),
            trading_enabled: false,
            timeouts: crate::config::Timeouts::default(),
            rss_warn_mb: 420,
            max_restarts_per_hour: 5,
            node4_poll_secs: 15,
            symbol_map: vec![("XAUUSD".into(), "XAUUSD.a".into())],
        }
    }

    #[test]
    fn the_startup_ini_has_every_section_mt5_documents() {
        let ini = start_ini(&config());
        for expected in [
            "[Common]",
            "Login=123456",
            "Password=hunter2",
            "Server=Deriv-Demo",
            "[Charts]",
            "[Experts]",
            "AllowLiveTrading=1",
            "Enabled=1",
            "[StartUp]",
            "Expert=Node4\\Mt5BridgeEA",
            "Symbol=XAUUSD",
            "Period=1",
            "ExpertParameters=Mt5BridgeEA.set",
        ] {
            assert!(ini.contains(expected), "startup ini is missing {expected}");
        }
        assert!(ini.contains("NewsEnable=0"), "news must stay off");
    }

    #[test]
    fn the_preset_carries_the_ea_inputs_and_widens_allowed_symbols() {
        let set = preset(&config());
        assert!(set.contains("InpBridgePort=5055"));
        assert!(set.contains("InpToken=ea-token"));
        assert!(set.contains("InpAllowedSymbols=XAUUSD,XAUUSD.a"));
        assert!(set.contains("InpMagicFilter=330033"));
    }

    #[test]
    fn an_empty_ea_token_produces_a_read_only_bridge_not_a_fake_token() {
        let mut cfg = config();
        cfg.ea_token = None;
        let set = preset(&cfg);
        assert!(set.contains("InpToken=\r\n"), "{set}");
        assert!(set.contains("InpToken="));
    }

    #[test]
    fn the_fallback_profile_points_at_the_same_ea_and_inputs() {
        let profile = chart_profile(&config());
        assert!(profile.contains("<expert>"));
        assert!(profile.contains("name=Node4\\Mt5BridgeEA"));
        assert!(profile.contains("InpBridgePort=5055"));
    }

    #[test]
    fn the_embedded_ea_is_the_real_source() {
        assert!(EA_SOURCE.contains("Mt5BridgeEA"));
        assert!(EA_SOURCE.contains("#property version"));
        // The EA's input names must match what the preset writes.
        for input in [
            "InpBridgeHost",
            "InpBridgePort",
            "InpToken",
            "InpAllowedSymbols",
            "InpHeartbeatSecs",
            "InpMagicFilter",
        ] {
            assert!(
                EA_SOURCE.contains(input),
                "EA input {input} is not in the source"
            );
        }
    }
}
